In [19]:
import numpy as np

# Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

a) произведение не определено

б) определено, размерность $2\times 3$

в) определено, размерность $8\times 8$

г)определено, размерность $4\times 4$

#### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix} 5 & -3\\ 3 & 5 \end{pmatrix}$

$A \cdot B = \begin{pmatrix} 4+0 & -1-10\\ 12+0 & -3+0 \end{pmatrix} = \begin{pmatrix} 4 & -11\\ 12 & -3 \end{pmatrix}$

#### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$\begin{pmatrix} 3 & 21\\ 9 & -18 \end{pmatrix} - \begin{pmatrix} 0 & 10\\ 4 & -2 \end{pmatrix} + \begin{pmatrix} 8 & -16\\ 4 & 4 \end{pmatrix} = \begin{pmatrix} 11 & -5\\ 9 & -12 \end{pmatrix}$ 

In [20]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5],[2, -1]])
C = np.array([[2, -4],[1, 1]])

In [21]:
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$AA^{T} = \begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix} \cdot \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3 \end{pmatrix} = 
\begin{pmatrix} 16+1 & 20-2 & 8+3\\ 20-2 & 25+4 & 10-6\\ 8+3 & 10-6 & 4 + 9 \end{pmatrix} = \begin{pmatrix} 17 & 18 & 11\\ 18 & 29 & 4 \\ 11 & 4 & 13 \end{pmatrix}$

$A^{T}A = \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3 \end{pmatrix} \cdot \begin{pmatrix} 4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix} = \begin{pmatrix} 16+25+4 & 4-10+6\\ 4-10+6 & 1+4+9 \end{pmatrix} = \begin{pmatrix} 45 & 0\\ 0 & 14 \end{pmatrix}$

#### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [22]:
def matrix_dot(X, Y):
    m = [[0 for i in range(len(Y[0]))] for el in range(len(X))]
    try:
        for i in range(len(Y[0])):
            for j in range(len(X)):
                for k in range(len(X[j])):
                    m [j][i]+= X[j][k] * Y[k][i]
    except IndexError:
        return 'Кол-во строк матрицы 1 не совпадает с кол-вом столбцов матрицы 2'
    return(m)

In [23]:
S = np.array([[8, 5, 3], [4, 6, 1], [0, 11, 9], [2, 7, 10], [2, 3, 1], [3, 3, 3]])
F = np.array([[1, 2, 3, 4, 6, 2], [2, 1, 1, 4, 1, 2], [2, 3, 4, 5, 6, 7], [1, 2, 1, 2, 1, 2]])

In [24]:
U = np.array([[1, 0], [2, 1], [10, 5]])
V = np.array([[2, 0, 0], [0, 0, 1]])

In [25]:
matrix_dot(F, S)

[[42, 102, 84], [36, 64, 63], [71, 146, 122], [28, 51, 41]]

In [26]:
matrix_dot(U, V)

[[2, 0, 0], [4, 0, 1], [20, 0, 5]]

In [27]:
F.dot(S)

array([[ 42, 102,  84],
       [ 36,  64,  63],
       [ 71, 146, 122],
       [ 28,  51,  41]])

In [28]:
U.dot(V)

array([[ 2,  0,  0],
       [ 4,  0,  1],
       [20,  0,  5]])

# Матрицы и матричные операции. Часть 2

#### __1.__ Вычислить определитель:

   a)

$\begin{vmatrix} sinx & -cosx\\ cosx & sinx \end{vmatrix}  = (sinx)^2 + (cosx)^2 = 1$


 б)
    
$\begin{vmatrix} 4 & 2 & 3\\ 0 & 5 & 1\\ 0 & 0 & 9 \end{vmatrix} = 4 * 5 * 9 = 180$
    


   в)

$\begin{vmatrix} 1 & 2 & 3\\4 & 5 & 6\\ 7 & 8 & 9 \end{vmatrix} = 1 * \begin{vmatrix} 5 & 6\\ 8 & 9\end{vmatrix} - 2 * 
\begin{vmatrix} 4 & 6\\ 7 & 9\end{vmatrix} + 3 * \begin{vmatrix} 4 & 5\\ 7 & 8\end{vmatrix} = 1* (-3) + 2 * 6  - 3 * 3 = 0$

#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) $4^2 = 16$

б) $4$

в) $4 \cdot 2 = 8$

#### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$ -2 * \begin{pmatrix} -14 & 6\\ 7 & 13\end{pmatrix} - 7 * \begin{pmatrix} 4 & 6\\ -3 & 13\end{pmatrix} -3 * \begin{pmatrix} 4 & -14\\ -3 & 7\end{pmatrix} = -2 * (-224) - 7 * 70 -3 * (-14) = 448 - 490 + 42 = 0$

определитель = 0 - значит матрица вырожденная

#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$


3я строка является суммой 1й и 2й, поэтому ее можно отбросить. Ранг 2

In [30]:
n = np.array([[1,2, 3], [1, 1, 1], [2,3, 4]])
np.linalg.matrix_rank(n)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

3я строка является суммой 1й и 2й, поэтому ее можно отбросить. Ранг 3

In [32]:
m = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(m)

3